### ISSUE TITLE
ValueError when running main_MultivariatePolyphonic.py

### ISSUE THREAD

**Issue by githubxiaowei** [lucapedrelli/DeepESN#3]
```
D:\ProgramFilesNoSpace\Miniconda3\envs\py36\python.exe C:/Users/MONKEY/Desktop/DeepESN-master/main_MultivariatePolyphonic.py
Traceback (most recent call last):
  File "C:/Users/MONKEY/Desktop/DeepESN-master/main_MultivariatePolyphonic.py", line 80, in <module>
    main()
  File "C:/Users/MONKEY/Desktop/DeepESN-master/main_MultivariatePolyphonic.py", line 61, in main
    states = deepESN.computeState(dataset.inputs, deepESN.IPconf.DeepIP)
  File "C:\Users\MONKEY\Desktop\DeepESN-master\DeepESN\DeepESN.py", line 206, in computeState
    states = self.computeDeepIntrinsicPlasticity(inputs)
  File "C:\Users\MONKEY\Desktop\DeepESN-master\DeepESN\DeepESN.py", line 174, in computeDeepIntrinsicPlasticity
    self.computeLayerState(inputs[i], layer, 1)   
  File "C:\Users\MONKEY\Desktop\DeepESN-master\DeepESN\DeepESN.py", line 130, in computeLayerState
    state[:,0:1] = (1-self.lis[layer]) * initialStatesLayer + self.lis[layer] * np.tanh( np.multiply(self.Gain[layer], self.W[layer].dot(initialStatesLayer) + input[:,0:1]) + self.Bias[layer])        
ValueError: could not broadcast input array from shape (100,100) into shape (100,1)

Process finished with exit code 1
```

**Comment by githubxiaowei** [comment]
bug fixed:
specify para 'DeepIP' in func computeDeepIntrinsicPlasticity in class DeepESN:
```py
             if len(inputs) == 1:
                    self.computeLayerState(inputs[0][:,self.IPconf.indexes], layer, 1, DeepIP = 1)
                else:
                    for i in self.IPconf.indexes:
                        self.computeLayerState(inputs[i], layer, 1, DeepIP = 1)
```
